# -*- coding: utf-8 -*-
"""lab6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YqVRvMVRoEA_K5EZUFIVad9LtZQR7XNd
"""

class House(object):

    house_type = "House"

    def __init__(self, floor, flats, front_doors, avg_apart_area):

        self.floor = floor
        self.flats = flats
        self.front_doors = front_doors
        self.avg_apart_area = avg_apart_area
    
    
    def __add__(self,other):
        
        return "Разница в: "+str(self.floor - other.floor)+" этажей \n" + "Разница в: " + str(self.flats - other.flats) +" квартир\n"+ "Разница в: " + str(self.front_doors - other.front_doors) + " Парадных\n" + "Разница ср.площадь квартиры в: " + str(self.avg_apart_area - other.avg_apart_area) + " кв.м"

    def __str__(self):
      return "Этажей: "+str(self.floor)+"\n" + "Всего квартир: " + str(self.flats) +"\n"+ "Парадных: " + str(self.front_doors) +"\n" + "Ср.площадь квартиры: " + str(self.avg_apart_area)
    
    def flat_floor_count(self):
        
        return int(self.flats/self.floor)

    def metters_count(self, a):

        return "Отношение жил/площади к площади земли " + str(self.floor*self.flats*self.front_doors*self.avg_apart_area/a)

    def info(self):

        return "Этажей: "+str(self.floor)+"\n" + "Всего квартир: " + str(self.flats) +"\n"+ "Парадных: " + str(self.front_doors) +"\n" + "Ср.площадь квартиры: " + str(self.avg_apart_area) +  "\n" + "Тип дома " + str(self.house_type)

class Cottage(House):

    house_type = "Cottage"

    def info(self):

        return "Этажей: "+str(self.floor)+"\n" + "Всего квартир: " + str(self.flats) +"\n"+ "Парадных: " + str(self.front_doors) +"\n" + "Ср.площадь квартиры: " + str(self.avg_apart_area) + "\n" + "Тип дома " + str(self.house_type)

class Skyscraper(House):

    house_type = "Skyscraper"

    def info(self):

        return "Этажей: "+str(self.floor)+"\n" + "Всего квартир: " + str(self.flats) +"\n"+ "Парадных: " + str(self.front_doors) +"\n" + "Ср.площадь квартиры: " + str(self.avg_apart_area) +  "\n" + "Тип дома " + str(self.house_type)


H1 = House(2,10,5,10.2)
H2 = House(2,5,3,13.5)
C1 = Cottage(2,5,3,13.5)
S1 = Skyscraper(2,5,3,13.5)
print(H2.metters_count(10))
print()
print(H2.flat_floor_count())
print()
print(H1 + H2)
print()
print(H2.info())
print()
print(S1.info())
print()
print(C1.info())